apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31001
    nodePort: 31001 # if you do not specify it will be random
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
