apiVersion: v1
kind: Pod
metadata:
  name: test-pod-sr
  labels:
    app: helloworld-sr
spec:
  containers:
  - name: k8s-demo
    image: wardviaene/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test-pod-sr
spec:
  ports:
  - port: 3000
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld-sr
