apiVersion: v1
kind: Pod
metadata:
  name: helloworld-with-provisioned
spec:
  containers:
  - name: myfrontend
    image: nginx
    volumeMounts:
    - mountPath: "/var/myVolume"
      name: my-vol
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: standard-10
